name: changelog_widgets
description: Flutter package to read 'CHANGELOG.md' file
  and display it in the app as a widget.
version: 1.1.0
homepage: https://github.com/DamianAldair/changelog_widgets
repository: https://github.com/DamianAldair/changelog_widgets

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.23

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any